/**
 * cron-index-drift adapter (REQ-CRON-DISC-004)
 *
 * Pre-push / CI gate that keeps the git-visible cron discoverability index
 * (.supernal/modules/crons.index.json + crons.index.md) honest. The index is a
 * read-only projection of the UNION of both cron stores (crons.json + per-board
 * SQLite), regenerated by `sc cron index`. If it drifts from the source, the
 * grep-able projection lies — defeating the whole point of §5.
 *
 * Spec: .supernal/docs/specs/platform/2026-06-24-cron-system-consolidation-sqlite-canonical.md §5 (R-D1, R-D4), §9 step 1
 *
 * ── What this adapter checks ───────────────────────────────────────────────────
 * The committed index is a pure function of declared files
 * (packages/cron-store/src/committed-cron-index.ts); live rows (crons.json,
 * SQLite, maintenance tasks) are never committed. This file-only rule checks
 * that the index exists, parses, and that every board row names its declared
 * source. Byte-equality with the declared files is `node scripts/cron-index-gen.mjs
 * --check` (pre-commit regenerates, pre-push checks each pushed commit); the live
 * declared-vs-aggregate check is `sc cron index --check`.
 *
 * Rule ID: cron-index-drift
 *
 * Diagnostics:
 *   - cron_index_missing       → error (index file absent)
 *   - cron_index_unparseable   → error (index JSON corrupt)
 *   - cron_index_stale         → error (the index predates declared-source tracking)
 *   - cron_index_undeclared    → error (a committed board row has declaredBy: null)
 *
 * No fallbacks (repo rule): a missing/unparseable index is a loud error.
 */

import fs from 'node:fs';
import path from 'node:path';
import type { Diagnostic, ValidatorAdapter, ValidatorContext } from '../core/types.js';

const CRONS_JSON_SEG = '/.supernal/modules/crons.json';
const CRON_INDEX_JSON_SEG = '/.supernal/modules/crons.index.json';
const CRON_INDEX_MD_SEG = '/.supernal/modules/crons.index.md';

interface CronIndexEntry {
  system?: string;
  boardId: string;
  cronId: string;
  declaredBy?: string | null;
}

interface CronIndexFile {
  version?: number;
  total?: number;
  entries?: CronIndexEntry[];
}

function normalize(p: string): string {
  return p.replace(/\\/g, '/');
}

function matchesAnySeg(filePath: string): boolean {
  const n = normalize(filePath);
  return (
    n.endsWith(CRONS_JSON_SEG) ||
    n.endsWith(CRON_INDEX_JSON_SEG) ||
    n.endsWith(CRON_INDEX_MD_SEG)
  );
}

function resolveMonorepoRoot(filePath: string, context: ValidatorContext): string {
  const n = normalize(filePath);
  for (const seg of [CRONS_JSON_SEG, CRON_INDEX_JSON_SEG, CRON_INDEX_MD_SEG]) {
    const idx = n.indexOf(seg);
    if (idx >= 0) return n.slice(0, idx);
  }
  return context.repoRoot;
}

export class CronIndexDriftAdapter implements ValidatorAdapter {
  id = 'cron-index-drift';

  /** Memoized per monorepo root — the diff runs at most once per root per run. */
  private cache = new Map<string, Diagnostic[]>();

  supports(filePath: string, _context: ValidatorContext): boolean {
    return matchesAnySeg(filePath);
  }

  async validate(filePath: string, context: ValidatorContext): Promise<Diagnostic[]> {
    const root = resolveMonorepoRoot(filePath, context);
    const cached = this.cache.get(root);
    if (cached) return [];
    const diagnostics = this.computeDrift(root);
    this.cache.set(root, diagnostics);
    return diagnostics;
  }

  private computeDrift(monorepoRoot: string): Diagnostic[] {
    const indexJsonPath = path.join(monorepoRoot, '.supernal', 'modules', 'crons.index.json');

    // ── The index file must exist + parse ──
    if (!fs.existsSync(indexJsonPath)) {
      return [
        {
          code: 'cron_index_missing',
          message:
            `.supernal/modules/crons.index.json is missing — the git-visible cron index is ` +
            `required. Run \`node scripts/cron-index-gen.mjs\` and commit it.`,
          severity: 'error',
          file: indexJsonPath,
          ruleId: this.id,
        },
      ];
    }

    let index: CronIndexFile;
    try {
      index = JSON.parse(fs.readFileSync(indexJsonPath, 'utf8')) as CronIndexFile;
    } catch (err) {
      return [
        {
          code: 'cron_index_unparseable',
          message: `.supernal/modules/crons.index.json could not be parsed: ${(err as Error).message}`,
          severity: 'error',
          file: indexJsonPath,
          ruleId: this.id,
        },
      ];
    }

    const diagnostics: Diagnostic[] = [];
    const boardEntries = (index.entries ?? []).filter((e) => e.system === 'board');
    if (boardEntries.some((e) => !('declaredBy' in e))) {
      diagnostics.push({
        code: 'cron_index_stale',
        message:
          `.supernal/modules/crons.index.json predates declared-source tracking (board rows have no ` +
          `declaredBy) — run \`sc cron index\` and commit the result.`,
        severity: 'error',
        file: indexJsonPath,
        ruleId: this.id,
      });
    } else {
      for (const e of boardEntries) {
        if (e.declaredBy !== null) continue;
        diagnostics.push({
          code: 'cron_index_undeclared',
          message:
            `Cron ${e.boardId}/${e.cronId} is in the aggregate with no declared source (no crons.yaml ` +
            `entry, not an sc-cron job, not soft-deleted). Restore its crons.yaml entry or run ` +
            `\`sc cron delete --id ${e.cronId} --board ${e.boardId} --reason "<why>"\`, then \`node scripts/cron-index-gen.mjs\`.`,
          severity: 'error',
          file: indexJsonPath,
          ruleId: this.id,
          details: { boardId: e.boardId, cronId: e.cronId },
        });
      }
    }

    return diagnostics;
  }
}
